### ISSUE TITLE
FEATURE: Support every x days, every x weeks, every month tracking

### ISSUE THREAD

**Issue by wakatara** [blinry/habitctl#10]
Might be a bit much to ask but this would be a great enhancement and much closer to some of the habit tracking I'm already doing (eg. Blog post every 2 weeks etc.).

**Comment by blinry** [comment]
To clarify: How would you like habitctl to behave? You can define habits which you want to do every x days already, by defining a number in the `habits` file. In #8 we discussed whether "satisfied" habits should be asked, and I think they should be tracked in some form. But maybe some simplified input mechanism would be great. What do you have in mind? :)

**Comment by wakatara** [comment]
I'm a bit embarrassed but you may be able to close this - I had not clued to the fact that you could set variable days since you had used the examples 1 for daily, 7 for a week, and 0 for just tracking.  :-/ 

Things that could be anchored to calendar, rather than days gone by, so, for instance, once a quarter rather than say every 90 days (again though, based on the model you have this may be breaking the minimalist philosophy you've got here... :-) )
