### ISSUE TITLE
Feature Request: Warning when consistency graph about to break

### ISSUE THREAD

**Issue by wakatara** [blinry/habitctl#21]
Something that was getting irksome at times in using the CLI every day. Sometimes for habits that are repeated over irregular day intervals of logner than a few days, it was often difficult ot realize when you were about to break the satisfying (or skipifying when I added that feature) of a habit. 

I added in an option for the ? to change to a ! on the last day that you have to perform a habit before breaking the consistency graph. 

It is available as a Pull Request to be merged in though should probably be code reviewed.
https://github.com/blinry/habitctl/pull/20

thanks!

**Comment by wakatara** [comment]
Note: I have not updated the README to reflect the change yet.

**Comment by blinry** [comment]
Closed by #20.
