### ISSUE TITLE
Tasks with n > 1 still get asked every day

### ISSUE THREAD

**Issue by baldrs** [blinry/habitctl#8]
So as I understand it should work like last time + n days, with every day asking if there was no last time or if it's overdue, but it does not. 

I have a record like:

```
7 Full apartment cleaning
```

Which gets asked every day, and that's fine, but I've also recorded it this Saturday when I've last did it, so I reckoned that it should start asking me next Saturday until I've clean apartment again.

**Comment by wakatara** [comment]
I actually consider this a feature, since I'll often do tasks again more than once in a week that I call weekly and it's useful to see those habits that I do end up doing more than weekly. So, I actually like the fact it asks.

**Comment by blinry** [comment]
I agree! If you did the next apartment cleaning on Friday, you surely would want to track that.

A possible compromise would be to combine all the currently satisfied habits into a list, and ask the user "did you do any of these?", to improve efficiency. I'll look into it, and I'm open to PRs! :) But I'm closing this issue, as the habits should be asked in some way.
